/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CatchAllImport } from './routes/$catchAll'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CatchAllRoute = CatchAllImport.update({
  id: '/$catchAll',
  path: '/$catchAll',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$catchAll': {
      id: '/$catchAll'
      path: '/$catchAll'
      fullPath: '/$catchAll'
      preLoaderRoute: typeof CatchAllImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$catchAll': typeof CatchAllRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$catchAll': typeof CatchAllRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$catchAll': typeof CatchAllRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$catchAll'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$catchAll'
  id: '__root__' | '/' | '/$catchAll'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatchAllRoute: typeof CatchAllRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatchAllRoute: CatchAllRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$catchAll"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$catchAll": {
      "filePath": "$catchAll.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
